name: Build and test images once a month

# Controls when the action will run. 
on:
  schedule:
  # Triggers the workflow once a month
  - cron: "0 9 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildandtest:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
      matrix:
        image: ["sharedpy3keras1.2", "mpra-dragonn", "extended_coda", "mmsplice",
          "mmsplice-mtsplice", "deepmel", "framepool", "kipoisplice", "deeptarget",
          "attentivechrome", "bpnet-oskn", "seqvec"]
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and test ${{ matrix.image }}
      run: |
        docker build -f dockerfiles/Dockerfile.kipoi-base-env -t haimasree/kipoi-docker:kipoi-base-env . 
        docker build -f dockerfiles/Dockerfile.${{ matrix.image }} -t haimasree/kipoi-docker:${{ matrix.image }} . 
        pytest -s test-containers/test_containers_from_command_line.py --image=haimasree/kipoi-docker:${{ matrix.image }} 
        docker system prune -a -f


  # Need to create two separate jobs for sharedpy3keras2 as it is not possible to test all the compatible model groups within the allotted time of 6 hours
  buildandtestsharedpy3keras2:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
      matrix:
        modelgroup: ["Basenji,Basset,HAL,DeepSEA,Optimus_5Prime,labranchor,CleTimer,SiSp,FactorNet,MaxEntScan,pwm_HOCOMOCO",
          "DeepBind,lsgkm-SVM", "rbp_eclip", "Xpresso"]
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and test sharedpy3keras2 with ${{ matrix.modelgroup }}
      run: |
        docker build -f dockerfiles/Dockerfile.kipoi-base-env -t haimasree/kipoi-docker:kipoi-base-env . 
        docker build -f dockerfiles/Dockerfile.sharedpy3keras2 -t haimasree/kipoi-docker:sharedpy3keras2 . 
        pytest -s test-containers/test_containers_from_command_line.py --image=haimasree/kipoi-docker:sharedpy3keras2 --modelgroup=${{ matrix.modelgroup }}
        docker system prune -a -f
