name:  Sync with https://github.com/kipoi/models

# Controls when the action will run. 
on:
  schedule:
  # Triggers the workflow once a month
  - cron: "0 9 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildandtest:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sync with kipoi model repo
      run: |
        python -m  modelupdater.updateoradd
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.8.2
      