# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test each model group with one representative model per group with compatible docker images

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -s test-containers/test_models_from_command_line.py --model=DeepCpG_DNA/Hou2016_HepG2_dna
        rm -rf /root/.kipoi/models/DeepCpG_DNA
        pytest -s test-containers/test_models_from_command_line.py --model=CpGenie/A549_ENCSR000DDI
        rm -rf /root/.kipoi/models/CpGenie
        pytest -s test-containers/test_models_from_command_line.py --model=Divergent421
        rm -rf /root/.kipoi/models/Divergent421
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=Basenji
        rm -rf /root/.kipoi/models/Basenji
        
        pytest -s test-containers/test_models_from_command_line.py --model=Basset
        rm -rf /root/.kipoi/models/Basset
        
        pytest -s test-containers/test_models_from_command_line.py --model=HAL
        rm -rf /root/.kipoi/models/HAL
        
        pytest -s test-containers/test_models_from_command_line.py --model=DeepSEA/variantEffects
        rm -rf /root/.kipoi/models/DeepSEA
        
        pytest -s test-containers/test_models_from_command_line.py --model=Optimus_5Prime
        rm -rf /root/.kipoi/models/Optimus_5Prime
        
        pytest -s test-containers/test_models_from_command_line.py --model=labranchor
        rm -rf /root/.kipoi/models/labranchor
        
        pytest -s test-containers/test_models_from_command_line.py --model=CleTimer/customBP
        rm -rf /root/.kipoi/models/CleTimer
        
        pytest -s test-containers/test_models_from_command_line.py --model=SiSp
        rm -rf /root/.kipoi/models/SiSp
        
        pytest -s test-containers/test_models_from_command_line.py --model=FactorNet/FOXA2/onePeak_Unique35_DGF
        rm -rf /root/.kipoi/models/FactorNet
        
        pytest -s test-containers/test_models_from_command_line.py --model=MaxEntScan/5prime
        rm -rf /root/.kipoi/models/MaxEntScan
        
        pytest -s test-containers/test_models_from_command_line.py --model=pwm_HOCOMOCO/human/AHR
        rm -rf /root/.kipoi/models/pwm_HOCOMOCO
        
        pytest -s test-containers/test_models_from_command_line.py --model=DeepBind/Arabidopsis_thaliana/RBP/D00283.001_RNAcompete_At_0284
        rm -rf /root/.kipoi/models/DeepBind
        
        pytest -s test-containers/test_models_from_command_line.py --model=lsgkm-SVM/Chip/OpenChrom/Cmyc/K562
        rm -rf /root/.kipoi/models/lsgkm-SVM
        
        pytest -s test-containers/test_models_from_command_line.py --model=rbp_eclip/AARS
        rm -rf /root/.kipoi/models/rbp_eclip
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=MPRA-DragoNN/DeepFactorizedModel
        rm -rf /root/.kipoi/models/MPRA-DragoNN
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=extended_coda
        rm -rf /root/.kipoi/models/extended_coda
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=MMSplice/deltaLogitPSI
        rm -rf /root/.kipoi/models/MMSplice
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=MMSplice/mtsplice
        rm -rf /root/.kipoi/models/CpGenie
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=DeepMEL
        rm -rf /root/.kipoi/models/DeepMEL
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=Framepool
        rm -rf /root/.kipoi/models/Framepool
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=KipoiSplice/4cons
        rm -rf /root/.kipoi/models/KipoiSplice
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=deepTarget
        rm -rf /root/.kipoi/models/deepTarget
        
        docker system prune -a -f
        pytest -s test-containers/test_models_from_command_line.py --model=AttentiveChrome/E003
        rm -rf /root/.kipoi/models/AttentiveChrome
        
        docker system prune -a -f        
        pytest -s test-containers/test_models_from_command_line.py --model=BPNet-OSKN
        rm -rf /root/.kipoi/models/BPNet-OSKN
        
        docker system prune -a -f
        
