# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test each model group with one representative model per group with compatible docker images

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -s test-containers/test_models_from_command_line.py --model=CpGenie/A549_ENCSR000DDI,Divergent421,DeepCpG_DNA/Hou2016_HepG2_dna
        docker system prune -a -f
        
        pytest -s test-containers/test_models_from_command_line.py --model=Basenji,Basset,HAL,DeepSEA/variantEffects,Optimus_5Prime,labranchor,CleTimer/customBP,SiSp,FactorNet/FOXA2/onePeak_Unique35_DGF,MaxEntScan/5prime,pwm_HOCOMOCO/human/AHR,DeepBind/Arabidopsis_thaliana/RBP/D00283.001_RNAcompete_At_0284,lsgkm-SVM/Chip/OpenChrom/Cmyc/K562,rbp_eclip/AARS
        docker system prune -a -f
        
        pytest -s test-containers/test_models_from_command_line.py --model=MPRA-DragoNN/DeepFactorizedModel
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=extended_coda
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=MMSplice/deltaLogitPSI
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=MMSplice/mtsplice
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=DeepMEL
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=Framepool
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=KipoiSplice/4
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=deepTarget
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=AttentiveChrome/E003
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=BPNet-OSKN
        docker system prune -a -f

        pytest -s test-containers/test_models_from_command_line.py --model=SeqVec/structure
        docker system prune -a -f